name: action workflow
 
on: [push, pull_request]

jobs:
  run-shell-command:
    runs-on: windows-latest
    steps:
      - name: List Files
        run:
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
          git clone git@hib:$GITHUB_REPOSITORY
         git checkout $GITHUB_SHA   
      - name: echo a string
        run: echo "Hello sethu"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: Powershell
        run: Get-Location   
      - name: python command
        run: |
          import platform
          print
          (platform.processor())
        shell: python
  run-windows-commands:
    runs-on: windows-latest
    steps:
      - name: Directory Powershell
        run:  Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash